//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjercicioPractico.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Book
    {
        public Book()
        {
            this.Sales = new HashSet<Sale>();
        }

        [Display(Name = "#")]
        public int id { get; set; }

        [Display(Name = "Titulo")]
        public string title { get; set; }

        [Display(Name = "Autor")]
        public string author { get; set; }

        [Display(Name = "Descripcion")]
        public string bookDescription { get; set; }

        public Nullable<System.DateTime> createdAt { get; set; }
    
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
